# Generated by Django 3.0.6 on 2020-06-03 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200531_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
    ]
