# Generated by Django 3.0.6 on 2020-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='car_model',
            field=models.CharField(max_length=200),
        ),
    ]
