# Generated by Django 3.0.6 on 2020-05-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20200531_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={},
        ),
        migrations.RemoveField(
            model_name='photos',
            name='create_at',
        ),
    ]
