# Generated by Django 3.0.6 on 2020-05-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20200531_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='image'),
        ),
    ]
