# Generated by Django 3.0.6 on 2020-05-31 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_auto_20200531_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
    ]
