# Generated by Django 3.0.6 on 2020-06-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_auto_20200531_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
