# Generated by Django 3.0.6 on 2020-06-01 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_auto_20200601_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ad',
            name='verification_email_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
