# Generated by Django 3.0.6 on 2020-06-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_auto_20200601_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='verification_email_sent_at',
            new_name='created_at',
        ),
    ]
