# Generated by Django 3.0.6 on 2020-06-01 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_cartype'),
        ('ads', '0015_auto_20200601_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='capacity',
        ),
        migrations.AddField(
            model_name='ad',
            name='car_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='type', to='brands.CarType'),
            preserve_default=False,
        ),
    ]
