# Generated by Django 3.0.6 on 2020-06-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_auto_20200601_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
