# Generated by Django 3.0.6 on 2020-06-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_auto_20200601_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
